# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

  jobs:
    pre_build:
      - echo "skip them"

    build:
      - mkdir -p _readthedocs/html
      - cp -r build/html/* _readthedocs/html/

    post_build:
      - echo "Done copying prebuilt HTML"

sphinx:
   configuration: source/conf.py

formats:
  - pdf
  - epub

python:
    install:
    - requirements: source/requirements.txt