# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

    commands: 
      - mkdir --parents _readthedocs/html/
      - cp --recursive build/html/* _readthedocs/html/

sphinx:
   configuration: source/conf.py

formats:
  - pdf
  - epub

python:
    install:
    - requirements: source/requirements.txt